//! Embedded causal graph engine for LEON3 flight firmware.
//!
//! The compiled causal graph binary (`causal_graph.bin`, generated by
//! `causal_graph/graph_compiler.py`) is embedded at compile time via
//! `include_bytes!()`. The ranker performs a **stack-only BFS** from
//! anomalous observable nodes back to root causes — no heap, no `Vec`.
//!
//! # Binary format (see `graph_compiler.py` for details)
//! ```text
//! [0..3]  Magic: 0xCA 0x05 0xAE 0x01
//! [4]     n_nodes (u8)
//! [5]     n_edges (u8)
//! [6..]   Node table: [node_id: u8, node_type: u8] × n_nodes
//! [..]    Edge table: [src: u8, dst: u8, weight: u8] × n_edges
//! ```
//!
//! # Memory footprint
//! `FlightGraph` lives entirely on the stack during `rank_root_causes()`.
//! The binary itself is in `.rodata` (flash) — zero RAM cost at rest.

// The compiled graph binary, embedded at build time (survives strip/LTO).
// Regenerate with: `python causal_graph/graph_compiler.py`
static GRAPH_BIN: &[u8] =
    include_bytes!("../../../causal_graph/causal_graph.bin");

// ── Format constants ──────────────────────────────────────────────────────────
pub const MAGIC: [u8; 4] = [0xCA, 0x05, 0xAE, 0x01];

pub const NODE_ROOT:         u8 = 0;
pub const NODE_INTERMEDIATE: u8 = 1;
pub const NODE_OBSERVABLE:   u8 = 2;

/// Compile-time node/edge caps (must be ≥ graph size for correct operation).
pub const MAX_NODES: usize = 96;
pub const MAX_EDGES: usize = 160;

/// Maximum BFS traversal depth (causal graph diameter is typically 4–5).
pub const MAX_DEPTH: usize = 7;

// ── Internal graph representation ─────────────────────────────────────────────

#[derive(Copy, Clone, Default)]
struct NodeMeta {
    node_type: u8,
}

#[derive(Copy, Clone, Default)]
struct Edge {
    src:    u8,   // source node ID
    dst:    u8,   // destination node ID
    weight: u8,   // edge weight: u8 → Q15 via weight_u8 * 32767 / 255
}

/// Stack-allocated parsed graph (lives only for the duration of `rank_root_causes`).
struct FlightGraph {
    n_nodes: usize,
    n_edges: usize,
    nodes:   [NodeMeta; MAX_NODES],
    edges:   [Edge;     MAX_EDGES],
}

/// Parse the embedded binary into a `FlightGraph`. Returns `None` on corrupt data.
fn load_graph() -> Option<FlightGraph> {
    let b = GRAPH_BIN;
    if b.len() < 6 { return None; }
    if b[0] != MAGIC[0] || b[1] != MAGIC[1] || b[2] != MAGIC[2] || b[3] != MAGIC[3] {
        return None;
    }

    let n_nodes = b[4] as usize;
    let n_edges = b[5] as usize;

    if n_nodes > MAX_NODES || n_edges > MAX_EDGES { return None; }

    let node_start = 6;
    let edge_start = node_start + n_nodes * 2;
    if b.len() < edge_start + n_edges * 3 { return None; }

    let mut graph = FlightGraph {
        n_nodes,
        n_edges,
        nodes: [NodeMeta::default(); MAX_NODES],
        edges: [Edge::default();     MAX_EDGES],
    };

    for i in 0..n_nodes {
        graph.nodes[i].node_type = b[node_start + i * 2 + 1];
    }

    for i in 0..n_edges {
        let base = edge_start + i * 3;
        graph.edges[i] = Edge {
            src:    b[base],
            dst:    b[base + 1],
            weight: b[base + 2],
        };
    }

    Some(graph)
}

// ── Public types ──────────────────────────────────────────────────────────────

/// Top-ranked root cause hypothesis from the causal engine.
#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct RootCauseHit {
    /// Node ID in the compiled graph (matches `aethelix_graph_ids.h` constants).
    pub node_id:   u8,
    /// Composite causal score in Q15 (path strength × anomaly severity).
    pub score_q15: i16,
    /// Number of causal hops from root cause to the triggering observable.
    pub path_hops: u8,
}

/// Rank root causes given a bitmask of anomalous channel observables.
///
/// `anomaly_mask` — bit N=1 means channel N (observable node) is anomalous.
/// `severity`     — Q15 severity per node index (from `ks_detector`).
///
/// Returns the top-3 root causes sorted by composite score, or
/// `node_id = 0xFF` for unused slots.
pub fn rank_root_causes(
    anomaly_mask: u32,
    severity:     &[i16; MAX_NODES],
) -> [RootCauseHit; 3] {
    let empty = RootCauseHit { node_id: 0xFF, score_q15: 0, path_hops: 0 };
    let mut result = [empty; 3];

    let graph = match load_graph() {
        Some(g) => g,
        None    => return result,
    };

    // Score accumulator per root-cause node
    let mut scores     = [0i32;   MAX_NODES];
    let mut path_depth = [0u8;    MAX_NODES];

    // For each anomalous observable, trace backwards to root causes via BFS
    for obs_id in 0..graph.n_nodes.min(32) {
        if (anomaly_mask >> obs_id) & 1 == 0 { continue; }
        if graph.nodes[obs_id].node_type != NODE_OBSERVABLE { continue; }

        let obs_sev = severity[obs_id] as i32;
        if obs_sev == 0 { continue; }

        // Stack-allocated BFS queue (no heap)
        let mut queue       = [0u8;  MAX_NODES];
        let mut weight_acc  = [0i32; MAX_NODES];
        let mut depth_arr   = [0u8;  MAX_NODES];
        let mut q_head      = 0usize;
        let mut q_tail      = 0usize;

        // Seed the BFS with the observable node
        queue[q_tail]            = obs_id as u8;
        weight_acc[obs_id]       = 32_767; // full strength at the observable
        q_tail                  += 1;

        while q_head < q_tail && q_head < MAX_NODES {
            let current = queue[q_head] as usize;
            q_head += 1;

            let depth = depth_arr[current] as usize;
            if depth >= MAX_DEPTH { continue; }

            // Find all edges where `dst == current` (reverse traversal)
            for e in 0..graph.n_edges {
                let edge = graph.edges[e];
                if edge.dst as usize != current { continue; }

                let parent = edge.src as usize;
                if parent >= graph.n_nodes { continue; }

                // Propagate path weight: w_parent = w_current * edge_weight / 255 (Q15)
                let edge_q15    = (edge.weight as i32).saturating_mul(32_767) / 255;
                let parent_w    = (weight_acc[current].saturating_mul(edge_q15)) >> 15;

                // Use maximum path weight (strongest evidence path wins)
                if parent_w > weight_acc[parent] {
                    weight_acc[parent] = parent_w;
                }

                if graph.nodes[parent].node_type == NODE_ROOT {
                    // Score = path_weight × observable_severity (both Q15, result Q15)
                    let contrib = (parent_w.saturating_mul(obs_sev)) >> 15;
                    scores[parent] = scores[parent].saturating_add(contrib);
                    if depth + 1 > path_depth[parent] as usize {
                        path_depth[parent] = (depth + 1) as u8;
                    }
                } else if q_tail < MAX_NODES {
                    // Enqueue intermediate for further traversal
                    queue[q_tail]     = parent as u8;
                    depth_arr[q_tail] = (depth + 1) as u8;
                    q_tail           += 1;
                }
            }
        }
    }

    // Extract top-3 root causes by score (simple selection sort, n ≤ 96)
    for slot in 0..3 {
        let mut best_id    = 0xFF_usize;
        let mut best_score = 0i32;

        for node_id in 0..graph.n_nodes {
            if graph.nodes[node_id].node_type != NODE_ROOT { continue; }
            if scores[node_id] <= best_score { continue; }

            // Ensure this node isn't already in the result
            let already = result[..slot].iter().any(|h| h.node_id == node_id as u8);
            if !already {
                best_score = scores[node_id];
                best_id    = node_id;
            }
        }

        if best_id < MAX_NODES {
            result[slot] = RootCauseHit {
                node_id:   best_id as u8,
                score_q15: best_score.clamp(0, i16::MAX as i32) as i16,
                path_hops: path_depth[best_id],
            };
        }
    }

    result
}

// ── Unit tests ────────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_graph_loads_successfully() {
        // If the binary was generated correctly, load_graph() must succeed
        let graph = load_graph();
        assert!(graph.is_some(), "causal_graph.bin failed to load");
        let g = graph.unwrap();
        assert!(g.n_nodes > 0, "Graph must have at least one node");
        assert!(g.n_edges > 0, "Graph must have at least one edge");
    }

    #[test]
    fn test_no_anomaly_returns_no_fault() {
        let severity = [0i16; MAX_NODES];
        let hits = rank_root_causes(0, &severity);
        // All slots should be empty (0xFF) when no anomaly is present
        assert_eq!(hits[0].node_id, 0xFF);
    }
}

// ── Kani proofs ───────────────────────────────────────────────────────────────
#[cfg(kani)]
mod kani_proofs {
    use super::*;

    #[kani::proof]
    fn prove_rank_root_causes_never_panics() {
        let mask: u32         = kani::any();
        let severity          = [0i16; MAX_NODES];
        let _ = rank_root_causes(mask, &severity);
    }
}
