/* aethelix_graph_ids.h
 * Auto-generated by causal_graph/graph_compiler.py — DO NOT EDIT.
 * Root-cause fault IDs matching the compiled causal_graph.bin.
 */

#ifndef AETHELIX_GRAPH_IDS_H
#define AETHELIX_GRAPH_IDS_H

#define AETHELIX_GRAPH_N_NODES  52U
#define AETHELIX_GRAPH_N_EDGES  58U

/* Root cause node IDs (match compiled graph binary) */
#define AETHELIX_FAULT_ANTENNA_POINTING_ERROR                0x00U
#define AETHELIX_FAULT_BATTERY_AGING                         0x01U
#define AETHELIX_FAULT_BATTERY_HEATSINK_FAILURE              0x04U
#define AETHELIX_FAULT_BATTERY_THERMAL                       0x08U
#define AETHELIX_FAULT_BER_SPIKE                             0x0BU
#define AETHELIX_FAULT_FUEL_PRESSURE_ANOMALY                 0x12U
#define AETHELIX_FAULT_GYRO_DRIFT                            0x14U
#define AETHELIX_FAULT_MAGNETORQUER_ANOMALY                  0x16U
#define AETHELIX_FAULT_MEMORY_CORRUPTION                     0x17U
#define AETHELIX_FAULT_PANEL_INSULATION_DEGRADATION          0x19U
#define AETHELIX_FAULT_PAYLOAD_RADIATOR_DEGRADATION          0x1AU
#define AETHELIX_FAULT_PCDU_REGULATOR_FAILURE                0x1DU
#define AETHELIX_FAULT_SENSOR_BIAS                           0x22U
#define AETHELIX_FAULT_SOFTWARE_EXCEPTION                    0x23U
#define AETHELIX_FAULT_SOLAR_DEGRADATION                     0x24U
#define AETHELIX_FAULT_THRUSTER_VALVE_FAULT                  0x2DU
#define AETHELIX_FAULT_TRANSPONDER_FAULT                     0x2EU
#define AETHELIX_FAULT_WATCHDOG_RESET_FAULT                  0x30U
#define AETHELIX_FAULT_WHEEL_FRICTION                        0x32U

#define AETHELIX_FAULT_NONE  0xFFU  /* No fault detected */

#endif /* AETHELIX_GRAPH_IDS_H */
